### ISSUE TITLE
segmentation fault when `deepcopy` on LibGEOS.Polygon

### ISSUE THREAD

**Issue by goretkin** [JuliaGeo/LibGEOS.jl#57] opened 2018-11-30 17:31 UTC
I think doing `deepcopy` on a `LibGEOS.Polygon` causes (not reliably) a segfault. I will try to produce an example later.

My guess is that a C++ destructor is getting called, but julia still holds a pointer, but I have not looked into it.

**Comment by yeesian** [comment] 2019-03-29 19:45
This might be related to #58 and #59, so I want to spend some time digging into it to make sure it has been addressed before closing this issue. Thanks for bringing it up!

**Comment by visr** [comment] 2019-05-12 19:54
@yeesian ok to close or do you want to check further?

I can't seem to reproduce it by a simple:
```julia
using LibGEOS
polygon = readgeom("POLYGON((0 0,1 0,1 1,0 0))")
for _ = 1:10_000_000
    deepcopy(polygon)
end
```

But yes, if you have a reproducer that triggers this, it'd be good to know.

**Comment by yeesian** [comment] 2019-05-12 19:58
I think it's okay to close since there's no reproducable example.

**Closed by yeesian** 2019-05-12 19:58 UTC
